<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Ishant" failures="1" tests="6" name="Test" time="123.45" errors="0" timestamp="2024-06-27T21:24:36 IST">
  <testcase classname="amazon.retryDemo.RetryTestAmazon" name="launchAmazon" time="30.19">
    <skipped/>
  </testcase> <!-- launchAmazon -->
  <testcase classname="amazon.retryDemo.RetryTestAmazon" name="launchAmazon" time="15.224">
    <skipped/>
  </testcase> <!-- launchAmazon -->
  <testcase classname="amazon.retryDemo.RetryTestAmazon" name="launchAmazon" time="26.766">
    <skipped/>
  </testcase> <!-- launchAmazon -->
  <testcase classname="amazon.retryDemo.RetryTestAmazon" name="launchAmazon" time="14.951">
    <skipped/>
  </testcase> <!-- launchAmazon -->
  <testcase classname="amazon.retryDemo.RetryTestAmazon" name="launchAmazon" time="16.688">
    <skipped/>
  </testcase> <!-- launchAmazon -->
  <testcase classname="amazon.retryDemo.RetryTestAmazon" name="launchAmazon" time="19.516">
    <failure type="java.lang.AssertionError" message="Test case 1 failed expected [6] but found [2]">
      <![CDATA[java.lang.AssertionError: Test case 1 failed expected [6] but found [2]
at amazon.retryDemo.RetryTestAmazon.launchAmazon(RetryTestAmazon.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- launchAmazon -->
</testsuite> <!-- Test -->
